#############################################################################
# Makefile for building: prova2
# Generated by qmake (2.01a) (Qt 4.8.7) on: dom dic 10 19:49:09 2017
# Project:  prova2.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile prova2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = analogclock.cpp \
		calaix.cpp \
		callinfo.cpp \
		main.cpp \
		messageinfo.cpp \
		opiwatch.cpp \
		tb_calaix.cpp \
		calculadora.cpp moc_analogclock.cpp \
		moc_calaix.cpp \
		moc_callinfo.cpp \
		moc_messageinfo.cpp \
		moc_opiwatch.cpp \
		moc_tb_calaix.cpp \
		moc_calculadora.cpp
OBJECTS       = analogclock.o \
		calaix.o \
		callinfo.o \
		main.o \
		messageinfo.o \
		opiwatch.o \
		tb_calaix.o \
		calculadora.o \
		moc_analogclock.o \
		moc_calaix.o \
		moc_callinfo.o \
		moc_messageinfo.o \
		moc_opiwatch.o \
		moc_tb_calaix.o \
		moc_calculadora.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		prova2.pro
QMAKE_TARGET  = prova2
DESTDIR       = 
TARGET        = prova2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_analogclock.h ui_calaix.h ui_callinfo.h ui_messageinfo.h ui_tb_calaix.h ui_opiwatch.h ui_calculadora.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: prova2.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile prova2.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile prova2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/prova21.0.0 || $(MKDIR) .tmp/prova21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/prova21.0.0/ && $(COPY_FILE) --parents analogclock.h calaix.h callinfo.h messageinfo.h opiwatch.h tb_calaix.h calculadora.h .tmp/prova21.0.0/ && $(COPY_FILE) --parents analogclock.cpp calaix.cpp callinfo.cpp main.cpp messageinfo.cpp opiwatch.cpp tb_calaix.cpp calculadora.cpp .tmp/prova21.0.0/ && $(COPY_FILE) --parents analogclock.ui calaix.ui callinfo.ui messageinfo.ui tb_calaix.ui opiwatch.ui calculadora.ui .tmp/prova21.0.0/ && (cd `dirname .tmp/prova21.0.0` && $(TAR) prova21.0.0.tar prova21.0.0 && $(COMPRESS) prova21.0.0.tar) && $(MOVE) `dirname .tmp/prova21.0.0`/prova21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/prova21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_analogclock.cpp moc_calaix.cpp moc_callinfo.cpp moc_messageinfo.cpp moc_opiwatch.cpp moc_tb_calaix.cpp moc_calculadora.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_analogclock.cpp moc_calaix.cpp moc_callinfo.cpp moc_messageinfo.cpp moc_opiwatch.cpp moc_tb_calaix.cpp moc_calculadora.cpp
moc_analogclock.cpp: analogclock.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) analogclock.h -o moc_analogclock.cpp

moc_calaix.cpp: calaix.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) calaix.h -o moc_calaix.cpp

moc_callinfo.cpp: callinfo.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) callinfo.h -o moc_callinfo.cpp

moc_messageinfo.cpp: messageinfo.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) messageinfo.h -o moc_messageinfo.cpp

moc_opiwatch.cpp: opiwatch.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) opiwatch.h -o moc_opiwatch.cpp

moc_tb_calaix.cpp: tb_calaix.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) tb_calaix.h -o moc_tb_calaix.cpp

moc_calculadora.cpp: calculadora.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) calculadora.h -o moc_calculadora.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_analogclock.h ui_calaix.h ui_callinfo.h ui_messageinfo.h ui_tb_calaix.h ui_opiwatch.h ui_calculadora.h
compiler_uic_clean:
	-$(DEL_FILE) ui_analogclock.h ui_calaix.h ui_callinfo.h ui_messageinfo.h ui_tb_calaix.h ui_opiwatch.h ui_calculadora.h
ui_analogclock.h: analogclock.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic analogclock.ui -o ui_analogclock.h

ui_calaix.h: calaix.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic calaix.ui -o ui_calaix.h

ui_callinfo.h: callinfo.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic callinfo.ui -o ui_callinfo.h

ui_messageinfo.h: messageinfo.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic messageinfo.ui -o ui_messageinfo.h

ui_tb_calaix.h: tb_calaix.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic tb_calaix.ui -o ui_tb_calaix.h

ui_opiwatch.h: opiwatch.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic opiwatch.ui -o ui_opiwatch.h

ui_calculadora.h: calculadora.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic calculadora.ui -o ui_calculadora.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

analogclock.o: analogclock.cpp analogclock.h \
		ui_analogclock.h \
		opiwatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analogclock.o analogclock.cpp

calaix.o: calaix.cpp calaix.h \
		ui_calaix.h \
		calculadora.h \
		ui_calculadora.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calaix.o calaix.cpp

callinfo.o: callinfo.cpp callinfo.h \
		ui_callinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o callinfo.o callinfo.cpp

main.o: main.cpp opiwatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

messageinfo.o: messageinfo.cpp messageinfo.h \
		ui_messageinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o messageinfo.o messageinfo.cpp

opiwatch.o: opiwatch.cpp opiwatch.h \
		analogclock.h \
		messageinfo.h \
		callinfo.h \
		calaix.h \
		tb_calaix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opiwatch.o opiwatch.cpp

tb_calaix.o: tb_calaix.cpp tb_calaix.h \
		ui_tb_calaix.h \
		opiwatch.h \
		calaix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tb_calaix.o tb_calaix.cpp

calculadora.o: calculadora.cpp calculadora.h \
		ui_calculadora.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calculadora.o calculadora.cpp

moc_analogclock.o: moc_analogclock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_analogclock.o moc_analogclock.cpp

moc_calaix.o: moc_calaix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calaix.o moc_calaix.cpp

moc_callinfo.o: moc_callinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_callinfo.o moc_callinfo.cpp

moc_messageinfo.o: moc_messageinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_messageinfo.o moc_messageinfo.cpp

moc_opiwatch.o: moc_opiwatch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_opiwatch.o moc_opiwatch.cpp

moc_tb_calaix.o: moc_tb_calaix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tb_calaix.o moc_tb_calaix.cpp

moc_calculadora.o: moc_calculadora.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calculadora.o moc_calculadora.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

